GET http://localhost:3000

###

POST /auth/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "username": "ddge7",
    "password": "12345"

}


###

GET /users/me/5f9914d98669e53ee040b0b7 HTTP/1.1
Host: localhost:3000

